require:
  - rubocop-rspec

AllCops:
  NewCops: enable
  TargetRubyVersion: 2.7
  Exclude:
    - 'rubocop-core-integration/**/*'

Layout/LineLength:
  Max: 120

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*_spec.rb'
    - 'lib/tasks/*.rake'

RSpec/ExampleLength:
  Max: 15

RSpec/ContextWording:
  AllowedPatterns:
    - '^edge cases$'
    - '^set_ prefix edge cases$'

Naming/FileName:
  Exclude:
    - 'lib/rubocop-monolith-idioms.rb'

# Capybara cops can error on non-Capybara spec files
Capybara/RSpec/PredicateMatcher:
  Exclude:
    - 'spec/**/*'

